2025-07-12 14:37:40 [WARNING] <有可用的更新！前往更新器获取 <1.0.4> >
2025-07-12 14:37:45 [DEBUG] <权限检查通过>
2025-07-12 14:37:46 [DEBUG] <初始化完毕..启动{日常任务}模块>
2025-07-12 14:37:48 [DEBUG] <发现已存在的游戏窗口>
2025-07-12 14:37:51 [SUCCESS] <程序开始接管操作，请保持游戏画面处于前台，终止按下Alt键>
2025-07-12 14:37:52 [TRACE] <【现在处于主菜单】>
2025-07-12 14:37:52 [TRACE] <【目标出现】images/battery.png 置信度：0.9999994039535522>
2025-07-12 14:37:53 [INFO] <当前电量为：39，执行 0 次循环>
2025-07-12 14:37:53 [TRACE] <【现在处于主菜单】>
2025-07-12 14:37:54 [TRACE] <【目标出现】images/battery.png 置信度：0.9999996423721313>
2025-07-12 14:37:54 [INFO] <当前电量为：39，执行 0 次循环>
2025-07-12 14:37:54 [TRACE] <【现在处于主菜单】>
2025-07-12 14:37:55 [TRACE] <【目标出现】images/battery.png 置信度：0.9999998211860657>
2025-07-12 14:37:56 [ERROR] <----------------未知错误-------------------->
2025-07-12 14:37:56 [ERROR] <Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Utils.py", line 836, in run
    battery_remaining=battery_check()
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Utils.py", line 257, in battery_check
    result=int(result[0])
               ~~~~~~^^^
IndexError: list index out of range
>
2025-07-12 14:37:56 [WARNING] <程序已经结束，按回车键退出(Enter)>
