ÄãÓ¦¸Ã¿´²»¼ûÕâ¸ö[37m2025-06-26T21:43:11.371364+0800[0m [41m[1mCRITICAL[0m[41m[1m123[0m
¡¾·¢ÏÖÒÑ´æÔÚµÄÓÎÏ·´°¿Ú¡¿
¡¾ÏÖÔÚ´¦ÓÚÖ÷²Ëµ¥¡¿
¡¾Ä¿±ê³öÏÖ¡¿images/battery.png ÖÃĞÅ¶ÈÊÇ£º0.9999998211860657
Using CPU. Note: This module is much faster with a GPU.
-------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 747, in run
    battery=battery_check()    #»ñÈ¡ÌåÁ¦ĞÅÏ¢
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 252, in battery_check
    result=int(result[0])
               ~~~~~~^^^
IndexError: list index out of range

Exception:Ö÷Ïß³Ì³ö´í
°´»Ø³µ¼üÍË³ö(Enter)Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 747, in run
    battery=battery_check()    #»ñÈ¡ÌåÁ¦ĞÅÏ¢
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 252, in battery_check
    result=int(result[0])
               ~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 778, in <module>
    run()
    ~~~^^
  File "C:\Users\gelon\Desktop\Pytutorial\ZenlessZoneZero_Automation\ZA_Main.py", line 775, in run
    input('Exception:Ö÷Ïß³Ì³ö´í\n°´»Ø³µ¼üÍË³ö(Enter)')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
KeyboardInterrupt
